# config/cucumber.yml
##YAML Template
---
android: PLATFORM=android -r features/support -r features/android -r features/step_definitions

ios: PLATFORM=ios -r features/support -r features/ios -r features/step_definitions
